-- Starter catalogue seed for YAZ Education V18.
-- The website still has local TypeScript data as a fallback while the database is being populated.
-- These rows give Supabase a real starting catalogue and may be safely re-run.

insert into public.universities
(slug, name, short_name, arabic_name, city, institution_type, campus, overview_en, overview_ar, study_areas_en, study_areas_ar, official_url, logo_path, verified, verified_at)
values
('apu','Asia Pacific University of Technology & Innovation','APU','جامعة آسيا باسيفيك للتكنولوجيا والابتكار','Kuala Lumpur','Private university','Technology Park Malaysia, Bukit Jalil','Technology-focused private university with strengths in computing, digital innovation, engineering and industry-linked learning.','جامعة خاصة تركز على التكنولوجيا مع نقاط قوة في الحوسبة والابتكار الرقمي والهندسة والتعلم المرتبط بالصناعة.',array['Computing & IT','Artificial Intelligence & Data','Cybersecurity','Engineering','Business & FinTech','Design & Media'],array['الحوسبة وتقنية المعلومات','الذكاء الاصطناعي والبيانات','الأمن السيبراني','الهندسة','الأعمال والتقنية المالية','التصميم والإعلام'],'https://www.apu.edu.my/','/universities/apu.png',true,'2026-09-21'),
('taylors','Taylor''s University','Taylor''s','جامعة تايلورز','Subang Jaya','Private university','Taylor''s Lakeside Campus','Broad-based private university offering pathways from foundation through postgraduate study.','جامعة خاصة متعددة التخصصات تقدم مسارات من التأسيسي حتى الدراسات العليا.',array['Business','Computer Science','Engineering','Architecture & Design','Hospitality & Tourism','Law & Health Sciences'],array['الأعمال','علوم الحاسب','الهندسة','العمارة والتصميم','الضيافة والسياحة','القانون والعلوم الصحية'],'https://university.taylors.edu.my/','/universities/taylors.png',true,'2026-09-21'),
('ucsi','UCSI University','UCSI','جامعة UCSI','Kuala Lumpur','Private university','Kuala Lumpur campus','Private university with a broad portfolio spanning health sciences, engineering, business, computing, music and arts.','جامعة خاصة تقدم مجالات واسعة تشمل العلوم الصحية والهندسة والأعمال والحوسبة والموسيقى والفنون.',array['Health Sciences','Engineering','Business','Computer Science','Music & Arts','Hospitality'],array['العلوم الصحية','الهندسة','الأعمال','علوم الحاسب','الموسيقى والفنون','الضيافة'],'https://www.ucsiuniversity.edu.my/','/universities/ucsi.png',true,'2026-09-21'),
('mmu','Multimedia University','MMU','جامعة ملتيميديا MMU','Cyberjaya / Melaka','Private university','Cyberjaya and Melaka campuses','Private university known for technology, computing, engineering, creative multimedia and digital education.','جامعة خاصة معروفة بالتكنولوجيا والحوسبة والهندسة والوسائط الإبداعية والتعليم الرقمي.',array['Computing','Engineering','Creative Multimedia','Business','Law','Communication'],array['الحوسبة','الهندسة','الوسائط الإبداعية','الأعمال','القانون','الاتصال'],'https://www.mmu.edu.my/','/universities/mmu.png',true,'2026-09-21'),
('sunway','Sunway University','Sunway','جامعة صنواي','Bandar Sunway','Not-for-profit private university','Bandar Sunway, Selangor','Not-for-profit private university within the integrated Sunway City education environment.','جامعة خاصة غير ربحية ضمن بيئة Sunway City المتكاملة للتعليم والحياة الطلابية.',array['Business','Computing','Engineering & Technology','Arts','Hospitality','Health & Medical Sciences'],array['الأعمال','الحوسبة','الهندسة والتكنولوجيا','الفنون','الضيافة','العلوم الصحية والطبية'],'https://sunwayuniversity.edu.my/','/universities/sunway.png',true,'2026-09-21'),
('utm','Universiti Teknologi Malaysia','UTM','جامعة التكنولوجيا الماليزية UTM','Johor Bahru / Kuala Lumpur','Public research university','Main campus in Johor Bahru; campuses in Kuala Lumpur and Pagoh','Malaysian research university focused on engineering, science and technology.','جامعة بحثية ماليزية تركز على الهندسة والعلوم والتكنولوجيا.',array['Engineering','Computing','Science','Built Environment','Management','Education & Social Sciences'],array['الهندسة','الحوسبة','العلوم','البيئة المبنية','الإدارة','التربية والعلوم الاجتماعية'],'https://www.utm.my/','/universities/utm.png',true,'2026-09-21'),
('iium','International Islamic University Malaysia','IIUM','الجامعة الإسلامية العالمية بماليزيا','Gombak / Kuantan / Pagoh','Public university','Main campus in Gombak with additional campuses','Public university integrating professional education with Islamic values and a highly international student community.','جامعة حكومية تدمج التعليم المهني بالقيم الإسلامية وتخدم مجتمعاً طلابياً دولياً واسعاً.',array['Engineering','Information Technology','Law','Economics & Management','Islamic Studies & Human Sciences','Medicine & Health Sciences'],array['الهندسة','تقنية المعلومات','القانون','الاقتصاد والإدارة','الدراسات الإسلامية والعلوم الإنسانية','الطب والعلوم الصحية'],'https://www.iium.edu.my/','/universities/iium.png',true,'2026-09-21'),
('utem','Universiti Teknikal Malaysia Melaka','UTeM','الجامعة التقنية الماليزية ملقا UTeM','Melaka','Public technical university','Durian Tunggal / Ayer Keroh','Public technical university with application-oriented strengths in engineering, IT and technology management.','جامعة تقنية حكومية ذات توجه تطبيقي في الهندسة وتقنية المعلومات وإدارة التكنولوجيا.',array['Engineering','Information Technology','Technology Management'],array['الهندسة','تقنية المعلومات','إدارة التكنولوجيا'],'https://www.utem.edu.my/','/universities/utem.png',true,'2026-09-21'),
('usm','Universiti Sains Malaysia','USM','جامعة العلوم الماليزية USM','Penang','Public research university','Penang / Nibong Tebal / Kubang Kerian','Malaysian public research university with science, engineering, health, arts and social-science strengths.','جامعة بحثية حكومية ماليزية ذات نقاط قوة في العلوم والهندسة والصحة والفنون والعلوم الاجتماعية.',array['Science','Engineering','Health Sciences','Arts','Social Sciences'],array['العلوم','الهندسة','العلوم الصحية','الفنون','العلوم الاجتماعية'],'https://www.usm.my/','/universities/usm.png',true,'2026-09-21'),
('segi','SEGi University','SEGi','جامعة SEGi','Kota Damansara','Private university','Kota Damansara','Private university offering programmes across business, computing, engineering, health sciences and other fields.','جامعة خاصة تقدم برامج في الأعمال والحوسبة والهندسة والعلوم الصحية ومجالات أخرى.',array['Business','Computing','Engineering','Health Sciences','Hospitality'],array['الأعمال','الحوسبة','الهندسة','العلوم الصحية','الضيافة'],'https://www.segi.edu.my/','/universities/segi.png',true,'2026-09-21'),
('inti','INTI International University','INTI','جامعة INTI الدولية','Nilai','Private university','Nilai, Negeri Sembilan','Private university offering international pathways and programmes across business, computing, engineering and other fields.','جامعة خاصة تقدم مسارات دولية وبرامج في الأعمال والحوسبة والهندسة ومجالات أخرى.',array['Business','Computing','Engineering','Design','Hospitality'],array['الأعمال','الحوسبة','الهندسة','التصميم','الضيافة'],'https://newinti.edu.my/','/universities/inti.png',true,'2026-09-21'),
('help','HELP University','HELP','جامعة HELP','Kuala Lumpur / Subang','Private university','Kuala Lumpur / Subang','Private university with programmes in business, psychology, computing, law and other disciplines.','جامعة خاصة تقدم برامج في الأعمال وعلم النفس والحوسبة والقانون ومجالات أخرى.',array['Business','Psychology','Computing','Law','Communication'],array['الأعمال','علم النفس','الحوسبة','القانون','الاتصال'],'https://university.help.edu.my/','/universities/help.png',true,'2026-09-21'),
('cyberjaya','University of Cyberjaya','UoC','جامعة سايبرجايا','Cyberjaya','Private university','Cyberjaya','Private university with major strengths in medicine, health sciences and related professional fields.','جامعة خاصة ذات نقاط قوة رئيسية في الطب والعلوم الصحية والمجالات المهنية المرتبطة بها.',array['Medicine','Health Sciences','Business','Psychology','Education'],array['الطب','العلوم الصحية','الأعمال','علم النفس','التربية'],'https://cyberjaya.edu.my/','/universities/cyberjaya.png',true,'2026-09-21'),
('city','City University Malaysia','City University','جامعة سيتي ماليزيا','Petaling Jaya','Private university','Petaling Jaya','Private university offering programmes across business, computing, engineering, design and education.','جامعة خاصة تقدم برامج في الأعمال والحوسبة والهندسة والتصميم والتربية.',array['Business','Computing','Engineering','Design','Education'],array['الأعمال','الحوسبة','الهندسة','التصميم','التربية'],'https://city.edu.my/','/universities/city.png',true,'2026-09-21'),
('taylors-college','Taylor''s College','Taylor''s College','كلية تايلورز','Subang Jaya','Private college','Taylor''s Lakeside Campus','Private college specialising in pre-university, foundation, diploma and professional-accounting pathways.','كلية خاصة تركز على برامج ما قبل الجامعة والتأسيسي والدبلوم والمسارات المهنية في المحاسبة.',array['GCE A Level','SACE','Foundation','Diploma','Professional Accounting'],array['GCE A Level','SACE','التأسيسي','الدبلوم','المحاسبة المهنية'],'https://college.taylors.edu.my/','/universities/taylors-college.png',true,'2026-09-21')
on conflict (slug) do update set
  name=excluded.name, short_name=excluded.short_name, arabic_name=excluded.arabic_name,
  city=excluded.city, institution_type=excluded.institution_type, campus=excluded.campus,
  overview_en=excluded.overview_en, overview_ar=excluded.overview_ar,
  study_areas_en=excluded.study_areas_en, study_areas_ar=excluded.study_areas_ar,
  official_url=excluded.official_url, logo_path=excluded.logo_path,
  verified=excluded.verified, verified_at=excluded.verified_at, updated_at=now();

insert into public.language_institutes
(slug,name,short_name,arabic_name,city,institution_type,overview_en,overview_ar,course_types_en,course_types_ar,official_url,logo_path,verified,verified_at)
values
('bright','Bright Language Center','Bright','معهد برايت ماليزيا','Kuala Lumpur','English language centre','English-language centre in central Kuala Lumpur offering intensive English, IELTS preparation, private classes, online learning and seasonal camps.','مركز لتعليم اللغة الإنجليزية في وسط كوالالمبور يقدم الإنجليزية المكثفة والتحضير لـ IELTS والدروس الخاصة والتعلم عبر الإنترنت والبرامج الموسمية.',array['Intensive English','IELTS Preparation','Private Classes','Online English','Summer & Winter Camps'],array['الإنجليزية المكثفة','التحضير لـ IELTS','الدروس الخاصة','الإنجليزية عبر الإنترنت','المعسكرات الصيفية والشتوية'],'https://bright.edu.my/en','/universities/bright.png',true,'2026-09-21'),
('els-malaysia','ELS Language Centres Malaysia','ELS','معاهد ELS ماليزيا','Kuala Lumpur / Subang Jaya / UPM / UTM','English language centre','English-language provider with multiple Malaysian centres and structured intensive English pathways.','مزود لتعليم اللغة الإنجليزية له عدة مراكز في ماليزيا ومسارات إنجليزية مكثفة ومنظمة.',array['Certified Intensive English Programme','General English','Workplace English','Test Preparation'],array['الإنجليزية المكثفة المعتمدة','الإنجليزية العامة','إنجليزية مكان العمل','التحضير للاختبارات'],'https://els.edu.my/','/yaz-logo.png',true,'2026-09-21'),
('elc-malaysia','English Language Company Malaysia','ELC','شركة اللغة الإنجليزية ELC ماليزيا','Bukit Bintang, Kuala Lumpur','English language centre','English school in Bukit Bintang offering general, academic, business, IELTS, junior and healthcare-focused English programmes.','مدرسة لغة إنجليزية في بوكيت بينتانج تقدم الإنجليزية العامة والأكاديمية وإنجليزية الأعمال وIELTS وبرامج الناشئين والقطاع الصحي.',array['General English','Business English','Academic English','IELTS','Junior Program','OET Preparation'],array['الإنجليزية العامة','إنجليزية الأعمال','الإنجليزية الأكاديمية','IELTS','برنامج الناشئين','التحضير لـ OET'],'https://elcmy.edu.my/','/yaz-logo.png',true,'2026-09-21')
on conflict (slug) do update set
  name=excluded.name, short_name=excluded.short_name, arabic_name=excluded.arabic_name,
  city=excluded.city, institution_type=excluded.institution_type,
  overview_en=excluded.overview_en, overview_ar=excluded.overview_ar,
  course_types_en=excluded.course_types_en, course_types_ar=excluded.course_types_ar,
  official_url=excluded.official_url, logo_path=excluded.logo_path,
  verified=excluded.verified, verified_at=excluded.verified_at, updated_at=now();

-- Verified programme-level seed rows.
insert into public.programmes
(slug, university_id, name, level, field, duration, campus, intakes, international_fee, specialisations, source_url, verified_at)
select 'apu-bsc-computer-science',u.id,'Bachelor of Science (Honours) in Computer Science','Bachelor''s','Computer Science',null,null,'{}','RM108,500 total (official 2026 page; exclusions and applicable SST apply)','{}','https://www.apu.edu.my/course/bsc-hons-in-computer-science','2026-09-21' from public.universities u where u.slug='apu'
on conflict (slug) do nothing;

insert into public.programmes
(slug, university_id, name, level, field, duration, campus, intakes, international_fee, specialisations, source_url, verified_at)
select 'apu-bsc-ai',u.id,'Bachelor of Computer Science (Hons) (Artificial Intelligence)','Bachelor''s','Artificial Intelligence','3 years',null,array['28 September 2026','24 November 2026'],null,'{}','https://www.apu.edu.my/course/bsc-hons-in-computer-science-ai','2026-09-21' from public.universities u where u.slug='apu'
on conflict (slug) do nothing;

insert into public.programmes
(slug, university_id, name, level, field, duration, campus, intakes, international_fee, specialisations, source_url, verified_at)
select 'taylors-bcs',u.id,'Bachelor of Computer Science (Honours)','Bachelor''s','Computer Science','3 years','Taylor''s Lakeside Campus',array['February','April','September'],'USD 40,049 (official 2026 page; fees may be revised and applicable service tax is separate)',array['Data Science','Cyber Security','Mobile Computing','Artificial Intelligence'],'https://university.taylors.edu.my/en/study/explore-all-programmes/computer-science/undergraduate/bachelor-of-computer-science.html','2026-09-21' from public.universities u where u.slug='taylors'
on conflict (slug) do nothing;

insert into public.programmes
(slug, university_id, name, level, field, duration, campus, intakes, international_fee, specialisations, source_url, verified_at)
select 'mmu-bcs',u.id,'Bachelor of Computer Science (Honours)','Bachelor''s','Computer Science','3 years','Cyberjaya','{}',null,array['Software Engineering','Game Development','Data Science','Cybersecurity'],'https://www.mmu.edu.my/cyberjaya/undergraduate/information-technology/bachelor-of-computer-science-hons/','2026-09-21' from public.universities u where u.slug='mmu'
on conflict (slug) do nothing;
