-- V22.4: Batch 3 - Health, Built Environment, Psychology, Communication and Creative Media.
-- Programme names and availability verified against current official university pages on 2026-09-22.
-- Public tuition display remains disabled by YAZ policy.

WITH programme_data(university_slug, slug, name, level, field, duration, campus, intakes, source_url, verified_at, study_mode, application_notes_en) AS (
VALUES
  ('utm', 'utm-bsc-architecture', 'Bachelor of Science in Architecture with Honours', 'Bachelor''s', 'Architecture', NULL, 'UTM Johor Bahru', ARRAY['September 2026']::text[], 'https://admission.utm.my/offered-allcourses-international/', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('utm', 'utm-bachelor-quantity-surveying', 'Bachelor of Quantity Surveying with Honours', 'Bachelor''s', 'Quantity Surveying', NULL, 'UTM Johor Bahru', ARRAY['September 2026']::text[], 'https://admission.utm.my/offered-allcourses-international/', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('utm', 'utm-bsc-construction', 'Bachelor of Science in Construction with Honours', 'Bachelor''s', 'Construction Management', NULL, 'UTM Johor Bahru', ARRAY['September 2026']::text[], 'https://admission.utm.my/offered-allcourses-international/', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('utm', 'utm-bachelor-urban-regional-planning', 'Bachelor of Urban and Regional Planning with Honours', 'Bachelor''s', 'Urban Planning', NULL, 'UTM Johor Bahru', ARRAY['September 2026']::text[], 'https://admission.utm.my/offered-allcourses-international/', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('utm', 'utm-bachelor-landscape-architecture', 'Bachelor of Landscape Architecture with Honours', 'Bachelor''s', 'Landscape Architecture', NULL, 'UTM Johor Bahru', ARRAY['September 2026']::text[], 'https://admission.utm.my/offered-allcourses-international/', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('utm', 'utm-bachelor-geomatics-engineering', 'Bachelor of Geomatics Engineering with Honours', 'Bachelor''s', 'Geomatics & Geoinformatics', NULL, 'UTM Johor Bahru', ARRAY['September 2026']::text[], 'https://admission.utm.my/offered-allcourses-international/', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('utm', 'utm-bsc-geoinformatics', 'Bachelor of Science in Geoinformatics with Honours', 'Bachelor''s', 'Geomatics & Geoinformatics', NULL, 'UTM Johor Bahru', ARRAY['September 2026']::text[], 'https://admission.utm.my/offered-allcourses-international/', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('utm', 'utm-bsc-land-administration-development', 'Bachelor of Science in Land Administration and Development with Honours', 'Bachelor''s', 'Land Administration & Development', NULL, 'UTM Johor Bahru', ARRAY['September 2026']::text[], 'https://admission.utm.my/offered-allcourses-international/', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('utm', 'utm-bachelor-real-estate', 'Bachelor of Real Estate with Honours', 'Bachelor''s', 'Real Estate', NULL, 'UTM Johor Bahru', ARRAY['September 2026']::text[], 'https://builtsurvey.utm.my/academic/undergraduate/', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('taylors', 'taylors-bsc-architecture', 'Bachelor of Science (Honours) in Architecture', 'Bachelor''s', 'Architecture', '3 years', 'Taylor''s Lakeside Campus', ARRAY['February','April','September']::text[], 'https://university.taylors.edu.my/en/study/explore-all-programmes/architecture-building-and-design/undergraduate/bachelor-of-science-in-architecture.html', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('taylors', 'taylors-ba-interior-architecture', 'Bachelor of Arts (Honours) in Interior Architecture', 'Bachelor''s', 'Interior Architecture', '3.5 years', 'Taylor''s Lakeside Campus', ARRAY['February','April','September']::text[], 'https://university.taylors.edu.my/en/study/explore-all-programmes/architecture-building-and-design/undergraduate/bachelor-of-art-in-interior-architecture.html', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('taylors', 'taylors-bachelor-quantity-surveying', 'Bachelor of Quantity Surveying (Honours)', 'Bachelor''s', 'Quantity Surveying', '3.5 years', 'Taylor''s Lakeside Campus', ARRAY['February','April','September']::text[], 'https://university.taylors.edu.my/en/study/explore-all-programmes/architecture-building-and-design/undergraduate/bachelor-of-quantity-surveying.html', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('taylors', 'taylors-bsc-sustainable-digital-construction', 'Bachelor of Science (Honours) in Sustainable Digital Construction Management', 'Bachelor''s', 'Sustainable Digital Construction', '3 years', 'Taylor''s Lakeside Campus', ARRAY[]::text[], 'https://university.taylors.edu.my/en/study/explore-all-programmes/architecture-building-and-design.html', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('taylors', 'taylors-bachelor-psychology', 'Bachelor of Psychology (Honours)', 'Bachelor''s', 'Psychology', NULL, 'Taylor''s Lakeside Campus', ARRAY[]::text[], 'https://university.taylors.edu.my/en/study/explore-all-programmes.html', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('taylors', 'taylors-bachelor-international-relations', 'Bachelor of Social Science (Honours) in International Relations', 'Bachelor''s', 'International Relations', NULL, 'Taylor''s Lakeside Campus', ARRAY[]::text[], 'https://university.taylors.edu.my/en/study/explore-all-programmes.html', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('taylors', 'taylors-bachelor-pharmacy', 'Bachelor of Pharmacy (Honours)', 'Bachelor''s', 'Pharmacy', '4 years', 'Taylor''s Lakeside Campus', ARRAY['April','September']::text[], 'https://university.taylors.edu.my/en/study/explore-all-programmes/pharmacy/undergraduate/bachelor-of-pharmacy.html', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('taylors', 'taylors-bachelor-pharmaceutical-science', 'Bachelor of Pharmaceutical Science (Honours)', 'Bachelor''s', 'Pharmaceutical Science', NULL, 'Taylor''s Lakeside Campus', ARRAY[]::text[], 'https://university.taylors.edu.my/en/study/explore-all-programmes/pharmacy.html', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('taylors', 'taylors-mbbs', 'Bachelor of Medicine, Bachelor of Surgery (MBBS)', 'Bachelor''s', 'Medicine', '5 years', 'Taylor''s Lakeside Campus', ARRAY['April','September']::text[], 'https://university.taylors.edu.my/en/study/explore-all-programmes/medicine/undergraduate/bachelor-of-medicine-bachelor-of-surgery.html', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('ucsi', 'ucsi-doctor-medicine', 'Doctor of Medicine (MD)', 'Bachelor''s', 'Medicine', '5 years', 'UCSI Springhill', ARRAY['September']::text[], 'https://www.ucsiuniversity.edu.my/programmes/faculty-of-medicine-and-health-sciences', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('ucsi', 'ucsi-bachelor-nursing', 'Bachelor of Nursing (Hons)', 'Bachelor''s', 'Nursing', NULL, 'UCSI Springhill', ARRAY['January','July']::text[], 'https://www.ucsiuniversity.edu.my/intakes-and-calendar', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('ucsi', 'ucsi-bachelor-optometry', 'Bachelor of Optometry (Honours)', 'Bachelor''s', 'Optometry', NULL, 'UCSI Kuala Lumpur', ARRAY['February','September']::text[], 'https://www.ucsiuniversity.edu.my/intakes-and-calendar', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('ucsi', 'ucsi-bachelor-pharmacy', 'Bachelor of Pharmacy (Honours)', 'Bachelor''s', 'Pharmacy', '4 years', 'UCSI Kuala Lumpur', ARRAY['February','May','September']::text[], 'https://www.ucsiuniversity.edu.my/node/171', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('ucsi', 'ucsi-bsc-architecture', 'Bachelor of Science (Hons) in Architecture', 'Bachelor''s', 'Architecture', NULL, 'UCSI Kuala Lumpur', ARRAY['March','September']::text[], 'https://www.ucsiuniversity.edu.my/programmes/faculty-of-engineering-technology-and-built-environment/architecture', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('ucsi', 'ucsi-ba-interior-architecture', 'Bachelor of Arts (Hons) in Interior Architecture', 'Bachelor''s', 'Interior Architecture', '3.5 years', 'UCSI Kuala Lumpur', ARRAY['March','September']::text[], 'https://www.ucsiuniversity.edu.my/programmes/bachelor-arts-hons-interior-architecture', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('ucsi', 'ucsi-bachelor-quantity-surveying', 'Bachelor of Quantity Surveying (Hons)', 'Bachelor''s', 'Quantity Surveying', NULL, 'UCSI Kuala Lumpur', ARRAY['March','September']::text[], 'https://www.ucsiuniversity.edu.my/programmes/bachelor-quantity-surveying-hons', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('ucsi', 'ucsi-ba-psychology', 'BA (Hons) Psychology', 'Bachelor''s', 'Psychology', '3 years', 'UCSI Kuala Lumpur', ARRAY['January','May','September']::text[], 'https://www.ucsiuniversity.edu.my/programmes/ba-hons-psychology', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('sunway', 'sunway-doctor-medicine', 'Doctor of Medicine', 'Bachelor''s', 'Medicine', NULL, 'Bandar Sunway', ARRAY[]::text[], 'https://sunwayuniversity.edu.my/faculty-of-medical-and-life-sciences/courses', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('sunway', 'sunway-bachelor-nursing', 'Bachelor of Nursing (Honours)', 'Bachelor''s', 'Nursing', '4 years', 'Bandar Sunway', ARRAY['October']::text[], 'https://sunwayuniversity.edu.my/faculty-of-medical-and-life-sciences/courses/bachelor-of-nursing-honours', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('sunway', 'sunway-bsc-psychology', 'Bachelor of Science (Honours) in Psychology', 'Bachelor''s', 'Psychology', '3 years', 'Bandar Sunway', ARRAY['January','April','September']::text[], 'https://sunwayuniversity.edu.my/faculty-of-medical-and-life-sciences/courses/bachelor-of-science-honours-psychology', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('sunway', 'sunway-bsc-biomedicine', 'Bachelor of Science (Honours) Biomedicine', 'Bachelor''s', 'Biomedicine', NULL, 'Bandar Sunway', ARRAY[]::text[], 'https://sunwayuniversity.edu.my/faculty-of-medical-and-life-sciences/courses/bachelor-of-science-honours-biomedicine', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('sunway', 'sunway-bsc-medical-biotechnology', 'BSc (Hons) Medical Biotechnology', 'Bachelor''s', 'Medical Biotechnology', '3 years', 'Bandar Sunway', ARRAY['January','April','September']::text[], 'https://sunwayuniversity.edu.my/faculty-of-medical-and-life-sciences/courses/bsc-hons-medical-biotechnology', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('sunway', 'sunway-ba-communication', 'Bachelor of Arts (Hons) in Communication', 'Bachelor''s', 'Communication & Media', NULL, 'Bandar Sunway', ARRAY[]::text[], 'https://sunwayuniversity.edu.my/sunway-university-lancaster-university/programmes', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('sunway', 'sunway-ba-advertising-branding', 'Bachelor of Arts (Honours) in Advertising and Branding', 'Bachelor''s', 'Advertising & Branding', NULL, 'Bandar Sunway', ARRAY[]::text[], 'https://sunwayuniversity.edu.my/centre-professional-and-continuing-education/apela-courses', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('sunway', 'sunway-ba-design-communication', 'Bachelor of Arts (Honours) Design Communication', 'Bachelor''s', 'Design Communication', NULL, 'Bandar Sunway', ARRAY[]::text[], 'https://sunwayuniversity.edu.my/centre-professional-and-continuing-education/apela-courses', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('sunway', 'sunway-ba-digital-film-production', 'Bachelor of Arts (Honours) Digital Film Production', 'Bachelor''s', 'Digital Film Production', NULL, 'Bandar Sunway', ARRAY[]::text[], 'https://sunwayuniversity.edu.my/centre-professional-and-continuing-education/apela-courses', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('mmu', 'mmu-bachelor-strategic-communication', 'Bachelor in Communication (Honours) (Strategic Communication)', 'Bachelor''s', 'Strategic Communication', NULL, 'Cyberjaya', ARRAY[]::text[], 'https://www.mmu.edu.my/programmes-by-faculty-all/programmes-by-faculty-fac/bachelor-in-comm-hons-strategic-communication/', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('mmu', 'mmu-bachelor-advertising-design', 'Bachelor in Advertising Design (Honours)', 'Bachelor''s', 'Advertising & Branding', '3 years', 'Cyberjaya', ARRAY[]::text[], 'https://www.mmu.edu.my/programmes-by-faculty-all/programmes-by-faculty-fcm/advertising-design/', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('mmu', 'mmu-bachelor-animation', 'Bachelor in Animation (Honours)', 'Bachelor''s', 'Animation', NULL, 'Cyberjaya', ARRAY[]::text[], 'https://www.mmu.edu.my/programmes-by-faculty-all/programmes-by-faculty-fcm/bachelor-in-animation-hons/', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('mmu', 'mmu-bachelor-immersive-media-design', 'Bachelor in Immersive Media Design (Honours)', 'Bachelor''s', 'Immersive Media Design', NULL, 'Cyberjaya', ARRAY[]::text[], 'https://www.mmu.edu.my/programmes-by-faculty-all/programmes-by-faculty-fcm/bachelor-in-immersive-media-design/', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('mmu', 'mmu-bachelor-visual-effects', 'Bachelor in Visual Effects (Honours)', 'Bachelor''s', 'Visual Effects', NULL, 'Cyberjaya', ARRAY[]::text[], 'https://www.mmu.edu.my/programmes-by-faculty-all/programmes-by-faculty-fcm/bachelor-in-visual-effects-hons/', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.'),
  ('mmu', 'mmu-bachelor-cinematic-arts', 'Bachelor of Cinematic Arts (Honours)', 'Bachelor''s', 'Digital Film Production', '3 years', 'Johor', ARRAY[]::text[], 'https://www.mmu.edu.my/programmes-by-faculty-all/programmes-by-faculty-fca/bachelor-in-cinematic-arts-hons/', '2026-09-22'::date, 'Full-time', 'Programme confirmed on an official university page. Reconfirm current intakes, admission requirements and any tuition quotation before advising. Public fee display is disabled by YAZ policy.')

)
INSERT INTO public.programmes (
  slug, university_id, name, level, field, duration, campus, intakes, source_url, verified_at, study_mode, application_notes_en
)
SELECT
  p.slug, u.id, p.name, p.level, p.field, p.duration, p.campus, p.intakes, p.source_url, p.verified_at, p.study_mode, p.application_notes_en
FROM programme_data p
JOIN public.universities u ON u.slug = p.university_slug
ON CONFLICT (slug) DO UPDATE SET
  university_id = EXCLUDED.university_id,
  name = EXCLUDED.name,
  level = EXCLUDED.level,
  field = EXCLUDED.field,
  duration = EXCLUDED.duration,
  campus = EXCLUDED.campus,
  intakes = EXCLUDED.intakes,
  source_url = EXCLUDED.source_url,
  verified_at = EXCLUDED.verified_at,
  study_mode = EXCLUDED.study_mode,
  application_notes_en = EXCLUDED.application_notes_en,
  updated_at = now();


SELECT count(*) AS batch3_programme_count
FROM public.programmes
WHERE slug IN (
  'utm-bsc-architecture',
  'utm-bachelor-quantity-surveying',
  'utm-bsc-construction',
  'utm-bachelor-urban-regional-planning',
  'utm-bachelor-landscape-architecture',
  'utm-bachelor-geomatics-engineering',
  'utm-bsc-geoinformatics',
  'utm-bsc-land-administration-development',
  'utm-bachelor-real-estate',
  'taylors-bsc-architecture',
  'taylors-ba-interior-architecture',
  'taylors-bachelor-quantity-surveying',
  'taylors-bsc-sustainable-digital-construction',
  'taylors-bachelor-psychology',
  'taylors-bachelor-international-relations',
  'taylors-bachelor-pharmacy',
  'taylors-bachelor-pharmaceutical-science',
  'taylors-mbbs',
  'ucsi-doctor-medicine',
  'ucsi-bachelor-nursing',
  'ucsi-bachelor-optometry',
  'ucsi-bachelor-pharmacy',
  'ucsi-bsc-architecture',
  'ucsi-ba-interior-architecture',
  'ucsi-bachelor-quantity-surveying',
  'ucsi-ba-psychology',
  'sunway-doctor-medicine',
  'sunway-bachelor-nursing',
  'sunway-bsc-psychology',
  'sunway-bsc-biomedicine',
  'sunway-bsc-medical-biotechnology',
  'sunway-ba-communication',
  'sunway-ba-advertising-branding',
  'sunway-ba-design-communication',
  'sunway-ba-digital-film-production',
  'mmu-bachelor-strategic-communication',
  'mmu-bachelor-advertising-design',
  'mmu-bachelor-animation',
  'mmu-bachelor-immersive-media-design',
  'mmu-bachelor-visual-effects',
  'mmu-bachelor-cinematic-arts'
);
